### ISSUE TITLE
The latest (8.0.2-1) version is broken

### ISSUE THREAD

**Issue by rsichnyi** [iuscommunity-pkg/python35u-pip#1]
```
# yum install python35u-pip
...
Installed:                        
  python35u-pip.noarch 0:8.0.2-1.ius.centos6
...
# pip3.5 install -I --upgrade pip
...
Installing collected packages: pip
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python3.5/site-packages/pip/commands/install.py", line 326, in run
    prefix=options.prefix_path,
  File "/usr/lib/python3.5/site-packages/pip/req/req_set.py", line 731, in install
    **kwargs
TypeError: install() got an unexpected keyword argument 'strip_file_prefix'
```

seems like the problem is in the patch, non-rpm installation works well:

```
# yum remove python35u-pip
...
# curl https://bootstrap.pypa.io/get-pip.py | python3.5
...
Successfully installed pip-8.0.2
# pip3.5 install -I --upgrade pip
...
Successfully installed pip-8.0.2
```

**Comment by michaeldfallen** [comment]
:+1: Can confirm this is causing issue for me too.

**Comment by octarine** [comment]
:+1: Happens to me as well

**Comment by b-harper** [comment]
@rsichny, thanks for taking the time to submit this bug.  I am able to recreate the issue as reported.  It seams that download, freeze, search and other pip command work.  We will look into this issue and hopefully have a fix soon.

-Ben

**Comment by carlwgeorge** [comment]
The likely fix will be wrapping Patch0 with a `0%{?build_wheel}` conditional.  I believe that patch is only needed for [Fedora's rewheel feature](https://docs.fedoraproject.org/en-US/Fedora/21/html/Release_Notes/sect-Release_Notes-Changes_for_Developers.html#idm225481723920), which we have left disabled in our python35u packages.

In spite of that pending correction, please don't run the command from your initial example.  Running this command successfully would modify the files installed by the package, which invalidates the package.  This is the equivalent of compiling software from source and overwriting the stock file locations.  On top of that, pip 8.0.2 is already the latest version.  As soon as the next version comes out, we'll package that too, and the updated will be delivered as valid packages.  There should never be a need to use pip3.5 to update itself outside of yum.

Instead of using pip3.5 to install Python modules, you can send us requests for new packages via our [wishlist](https://github.com/iuscommunity/wishlist), and we will consider shipping proper packages for them.  Alternatively, python35u ships with pyvenv-3.5, which lets you create [virtual environments](https://docs.python.org/3.5/library/venv.html) with vanilla pip and setuptools bootstrapped inside them.

**Comment by rsichnyi** [comment]
@b-harper @carlwgeorge trying pip install -I pip was just an example, actually i can not install ANY package i tried:

```
# pip3.5 install flake8
Collecting flake8
  Downloading flake8-2.5.2-py2.py3-none-any.whl
Collecting mccabe<0.5,>=0.2.1 (from flake8)
  Downloading mccabe-0.4.0-py2.py3-none-any.whl
Collecting pep8!=1.6.0,!=1.6.1,!=1.6.2,>=1.5.7 (from flake8)
  Downloading pep8-1.7.0-py2.py3-none-any.whl (41kB)
    100% |████████████████████████████████| 45kB 1.0MB/s 
Collecting pyflakes<1.1,>=0.8.1 (from flake8)
  Downloading pyflakes-1.0.0-py2.py3-none-any.whl (152kB)
    100% |████████████████████████████████| 155kB 1.5MB/s 
Installing collected packages: mccabe, pep8, pyflakes, flake8
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python3.5/site-packages/pip/commands/install.py", line 326, in run
    prefix=options.prefix_path,
  File "/usr/lib/python3.5/site-packages/pip/req/req_set.py", line 731, in install
    **kwargs
TypeError: install() got an unexpected keyword argument 'strip_file_prefix'
```

**Comment by rsichnyi** [comment]
> Instead of using pip3.5 to install Python modules, you can send us requests for new packages via our wishlist, and we will consider shipping proper packages for them

i doubt that it will work for my case - i'm trying to install packages to python virtual environment:

```
# pip3.5 install flake8 --root=./env --no-use-wheel --install-option=--force --install-option=--single-version-externally-managed --install-option=--install-lib=./env/lib/python3.5/site-packages --install-option=--install-scripts=./env/bin --install-option=--install-data=./env/data
...
TypeError: install() got an unexpected keyword argument 'strip_file_prefix'
```

**Comment by carlwgeorge** [comment]
@rsichny If you are using a virtual environment, use the pip that is bundled in the environment, not the system one.

```
[carl@test7 ~]$ pyvenv-3.5 env
[carl@test7 ~]$ . env/bin/activate
(env) [carl@test7 ~]$ which pip
~/env/bin/pip
(env) [carl@test7 ~]$ pip list
pip (7.1.2)
setuptools (18.2)
You are using pip version 7.1.2, however version 8.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(env) [carl@test7 ~]$ pip install --upgrade pip
Collecting pip
  Downloading pip-8.0.2-py2.py3-none-any.whl (1.2MB)
    100% |████████████████████████████████| 1.2MB 359kB/s 
Installing collected packages: pip
  Found existing installation: pip 7.1.2
    Uninstalling pip-7.1.2:
      Successfully uninstalled pip-7.1.2
Successfully installed pip-8.0.2
(env) [carl@test7 ~]$ pip install flake8
Collecting flake8
  Using cached flake8-2.5.2-py2.py3-none-any.whl
Collecting mccabe<0.5,>=0.2.1 (from flake8)
  Using cached mccabe-0.4.0-py2.py3-none-any.whl
Collecting pyflakes<1.1,>=0.8.1 (from flake8)
  Using cached pyflakes-1.0.0-py2.py3-none-any.whl
Collecting pep8!=1.6.0,!=1.6.1,!=1.6.2,>=1.5.7 (from flake8)
  Using cached pep8-1.7.0-py2.py3-none-any.whl
Installing collected packages: mccabe, pyflakes, pep8, flake8
Successfully installed flake8-2.5.2 mccabe-0.4.0 pep8-1.7.0 pyflakes-1.0.0
(env) [carl@test7 ~]$ pip list
flake8 (2.5.2)
mccabe (0.4.0)
pep8 (1.7.0)
pip (8.0.2)
pyflakes (1.0.0)
setuptools (18.2)
(env) [carl@test7 ~]$ deactivate 
[carl@test7 ~]$
```

**Comment by rsichnyi** [comment]
@carlwgeorge thanks, i know what are the ways to overcome the issue. what i say - the package is broken (as it should to be able to do things the way i do them way but it doesn't)

**Comment by carlwgeorge** [comment]
@rsichny Right, I agree that the package is still broken.  The temporary fix is to disable that [patch](https://github.com/iuscommunity-pkg/python35u-pip/blob/master/SOURCES/pip-1.5rc1-allow-stripping-prefix-from-wheel-RECORD-files.patch).  I found after some testing that just wrapping it in a conditional doesn't work for the bootstrap process, so we need to just comment it out for now.  The patch is needed for the rewheel bootstrap process, but that isn't currently enabled for python35u.  It is enabled for python34u, meaning that the bootstrap process is broken there.

We are going to proceed with the temporary fix of disabling the patch, until we can pinpoint exactly how the patch is not working.

**Comment by b-harper** [comment]
Upon further investigation, the patch does not need to get disabled, but just [updated correctly](https://github.com/iuscommunity-pkg/python35u-pip/commit/67a9c5d04c84150e8ebd6ec3881f1c9be8746e70).  New packages have been built and will be rolled out after tonight (US CST) automation run.

**Comment by rsichnyi** [comment]
fixed. thanks
